version: '3.0'
services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; gunicorn --bind 0.0.0.0:8000 NewsProviderAPI.wsgi'
    ports:
      - 8000:8000
    environment:
      PRODUCTION: 'true'
  db:
    image: postgres:12
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=challenge
      - POSTGRES_DB=challenge
